data:
  test_dir_mit: '/mnt/smb_share/SML/Aging_classifier/dataset_used_0730/Ctrl&OS_U2OS'
  key_name: 'U2OS'

  class_list: ['Oxidative', 'Young']
  dir_group: False
  dir_name_list: 'all' 

  file_format: '.tif' 
  divide_dataset_per_gpu: true
  organelle: mito 
  mode: 3D-WF (triple2X)
  img_size: 1024
  test_name: ['Young - U2OS', 'Oxidative stress - U2OS']

  img_edge: wavelet   
  dual_class: True
  sense_class: 'Oxidative stress'

---
train:
  random_seed: 420 
  num_epoch: 100 
  num_workers: 2 
  batch_size: 4 
  image_size: 1024 

  optimizer:
    mode: 'adamw'
    param:
      lr: 0.00001 
    betas:
        - 0.9
        - 0.999 
    weight_decay: 0.0001
    amsgrad: False
    scheduler:
      mode: MultiStep 
      decay_step: [50, 80]
      decay_gamma: 0.5
      warmup_lr: 0.00001
      warmup_epoch: 20

  loss:
    name: ['ce', 'fcl'] 
    ce:
      reduction: none
      weight: 2.
    fcl:
      reduction: none
      weight: 2

---
test:
  num_workers: 0
  batch_size: 1
---
model:
  name: VIT
  device: 'cuda:1'

  VIT:
    image_size: 1024
    patch_size: 32 
    num_classes: 2
    dim: 1280 
    depth: 16 
    heads: 16
    mlp_dim: 1024
    pool: 'cls' 
    dim_head: 256
    dropout: 0.3
    emb_dropout: 0.0 
    channels: 6
    latent_dim: 256 

---
log:
  print_yaml: False
  name: 'Aging_Classifier_Ctrl&OS_Test' 
  summary_interval: 1 
  val_interval: 10
  chkpt_interval: 10 
  log_dir: 'Aging_Classifier_Ctrl&OS_Test'
  show_last: True
  generate: True
  save: False
---
load:
  network_chkpt_path: Checkpoints/AC_Ctrl&OS.pth
  strict_load: True
